// Dataset: Mapa de la legaltech española 2026
// Base: Guía Legaltech de Derecho Práctico (derechopractico.es/guialegaltech/)
// + radar de lanzamientos IA jul 2025 – jul 2026 (prensa especializada / LinkedIn)
// Campos: n=nombre app, e=empresa, w=web (dominio), g=slug ficha en la guía,
// ci=ciudad sede española, pais=país (si no hay sede en España), c=categoría,
// ia=usa IA de forma central, nu=lanzada/aterrizada en los últimos 12 meses, d=servicio

window.LEGALTECH_DATA = {
  cats: [
    { k: "docs",        label: "Análisis y generación de documentos", color: "#B44E2C" },
    { k: "auto",        label: "Automatización documental y procesos", color: "#C98A2C" },
    { k: "bd",          label: "Bases de datos jurídicas",             color: "#2C6E63" },
    { k: "ciber",       label: "Ciberseguridad · Privacidad · Compliance", color: "#3E5C94" },
    { k: "digcomp",     label: "Legal DigComp (formación)",            color: "#7A5C99" },
    { k: "marketplace", label: "Marketplaces y redes de abogados",     color: "#B03A5B" },
    { k: "online",      label: "Servicios jurídicos online",           color: "#4E8A46" },
    { k: "gestion",     label: "Gestión de despachos y asesorías",     color: "#5B6470" }
  ],
  cities: {
    "Madrid":               { xy: [-3.703, 40.417], r: "Comunidad de Madrid" },
    "Barcelona":            { xy: [2.170, 41.387],  r: "Cataluña" },
    "Lleida":               { xy: [0.626, 41.617],  r: "Cataluña" },
    "Valencia":             { xy: [-0.376, 39.470], r: "Comunidad Valenciana" },
    "Alicante":             { xy: [-0.481, 38.345], r: "Comunidad Valenciana" },
    "Sevilla":              { xy: [-5.994, 37.389], r: "Andalucía" },
    "Granada":              { xy: [-3.598, 37.177], r: "Andalucía" },
    "Huelva":               { xy: [-6.944, 37.261], r: "Andalucía" },
    "Bilbao":               { xy: [-2.935, 43.263], r: "País Vasco" },
    "Donostia":             { xy: [-1.981, 43.318], r: "País Vasco" },
    "A Coruña":             { xy: [-8.406, 43.362], r: "Galicia" },
    "Santiago de Compostela": { xy: [-8.545, 42.878], r: "Galicia" },
    "Vigo":                 { xy: [-8.720, 42.240], r: "Galicia" },
    "Zaragoza":             { xy: [-0.877, 41.656], r: "Aragón" },
    "Pamplona":             { xy: [-1.646, 42.817], r: "Navarra" },
    "Murcia":               { xy: [-1.131, 37.987], r: "Región de Murcia" },
    "Palma":                { xy: [2.650, 39.570],  r: "Islas Baleares" },
    "Santander":            { xy: [-3.804, 43.463], r: "Cantabria" }
  },
  regiones: ["Andalucía","Aragón","Asturias","Cantabria","Castilla-La Mancha","Castilla y León","Cataluña","Comunidad de Madrid","Comunidad Valenciana","Extremadura","Galicia","Islas Baleares","Canarias","La Rioja","Navarra","País Vasco","Región de Murcia","Ceuta","Melilla"],
  items: [
    // ——— Análisis, revisión y generación de documentos ———
    { n: "IA Laboral", e: "IA Laboral Legal S.L.", w: "ialaboral.com", g: "ia-laboral", ci: "Palma", c: "docs", ia: 1, nu: 1, d: "IA generativa para documentación jurídico-laboral" },
    { n: "Lexroom.ai", e: "Lexroom (sede española, Madrid)", w: "lexroom.ai", g: null, ci: "Madrid", c: "docs", ia: 1, nu: 1, d: "IA para investigación y redacción jurídica con fuentes verificadas (CENDOJ). Llegó a España en 2026" },
    { n: "Avisio", e: "Avisio", w: "avisio.es", g: null, ci: null, pais: null, c: "docs", ia: 1, nu: 1, d: "IA que lee notificaciones de la AEAT y extrae importes, plazos y requerimientos" },
    { n: "DeducTA", e: "DeducTA", w: null, g: null, ci: null, pais: null, c: "docs", ia: 0, nu: 1, d: "Optimización fiscal asistida para autónomos y pymes" },
    { n: "Saga AI", e: "Saga International B.V.", w: "saga.law", g: "saga-ai", ci: null, pais: "Países Bajos", c: "docs", ia: 1, nu: 0, d: "Asistente de IA para análisis y redacción de documentos legales" },
    { n: "Aloi", e: "Aloi AI AB", w: "aloi.ai", g: "aloi", ci: null, pais: "Suecia", c: "docs", ia: 1, nu: 0, d: "IA para revisión y generación de documentos legales" },

    // ——— Automatización documental y de procesos ———
    { n: "Bigle", e: "Bigle Legal, S.L.", w: "biglelegal.com", g: null, ci: "Barcelona", c: "auto", ia: 1, nu: 0, d: "Suite CLM end-to-end con IA jurídica (Libra). Deloitte Fast 50 2026" },
    { n: "Cadrebox", e: "Legalbox Solutions, S.L.", w: "cadrebox.com", g: "cadrebox", ci: "Valencia", c: "auto", ia: 1, nu: 1, d: "Copiloto legal-contractual para startups: contratos con IA y data room de inversión" },
    { n: "DocuBoost", e: "DocuBoost", w: "docuboost.es", g: "docuboost", ci: "Barcelona", c: "auto", ia: 1, nu: 0, d: "Bots de IA para burocracia de despachos y procuradores" },
    { n: "Aidea Legal", e: "Aidea Legal", w: "aidealegal.com", g: "aidea-legal", ci: "Barcelona", c: "auto", ia: 1, nu: 0, d: "Automatización de procesos jurídicos con IA (Barcelona/Sevilla)" },
    { n: "LexDoka", e: "LexDoka, S.L.", w: "lexdoka.com", g: "lexdoka", ci: "Barcelona", c: "auto", ia: 0, nu: 0, d: "Ciclo de vida contractual: creación, negociación, firma" },
    { n: "Parallel", e: "Parallel Solutions, S.L.", w: "byparallel.com", g: null, ci: "Barcelona", c: "auto", ia: 1, nu: 0, d: "Automatización de tareas, recogida de información y procesos legales" },
    { n: "EdasNEO", e: "Zerocoma, S.L.", w: "zerocoma.com", g: "edasneo-by-zerocoma", ci: "Madrid", c: "auto", ia: 0, nu: 0, d: "Vigilancia y descarga de notificaciones de +13.500 organismos públicos" },
    { n: "Provingly", e: "Provingly, S.L.", w: "provingly.com", g: "provingly", ci: "Madrid", c: "auto", ia: 0, nu: 0, d: "Generación automatizada de documentos complejos a partir de datos" },
    { n: "Slango", e: "Slang Innovations, S.L.", w: "slango.io", g: "slango", ci: "Murcia", c: "auto", ia: 0, nu: 0, d: "Automatizaciones prediseñadas (Roboteka) para asesorías" },
    { n: "Agiloft", e: "Agiloft, Inc.", w: "agiloft.com", g: "agiloft", ci: null, pais: "EE. UU.", c: "auto", ia: 1, nu: 0, d: "CLM configurable con IA para departamentos jurídicos" },
    { n: "Avvoka", e: "Avvoka", w: "avvoka.com", g: "avvoka", ci: null, pais: "Reino Unido", c: "auto", ia: 1, nu: 0, d: "Automatización y negociación no-code de documentos" },
    { n: "ClauseBase", e: "ClauseBase BV", w: "clausebase.com", g: "clausebase", ci: null, pais: "Bélgica", c: "auto", ia: 0, nu: 0, d: "Redacción jurídica avanzada (ClauseBuddy, Clause9)" },

    // ——— Bases de datos jurídicas ———
    { n: "GenIA-L", e: "Lefebvre", w: "lefebvre.es", g: "genia-l", ci: "Madrid", c: "bd", ia: 1, nu: 0, d: "IA generativa jurídica sobre los fondos de Lefebvre" },
    { n: "Vincent", e: "vLex, part of Clio", w: "vlex.com", g: "vincent", ci: "Barcelona", c: "bd", ia: 1, nu: 0, d: "Asistente de investigación jurídica con IA de vLex" },
    { n: "vLex", e: "vLex, part of Clio", w: "vlex.es", g: null, ci: "Barcelona", c: "bd", ia: 1, nu: 0, d: "Base de datos jurídica global; adquirida por Clio en 2025" },
    { n: "Iberley", e: "Iberley Información Legal, S.L.", w: "iberley.es", g: "iberley", ci: "A Coruña", c: "bd", ia: 0, nu: 0, d: "Información y actualidad jurídica online" },
    { n: "Tirant Online", e: "Editorial Tirant lo Blanch", w: "tirantonline.com", g: null, ci: "Valencia", c: "bd", ia: 1, nu: 0, d: "Base de datos jurídica con asistente de IA (Sofía)" },
    { n: "La Ley Digital", e: "Aranzadi LA LEY", w: "laleynext.es", g: null, ci: "Madrid", c: "bd", ia: 0, nu: 0, d: "Base de datos de legislación, jurisprudencia y doctrina" },
    { n: "Jurimetría", e: "Aranzadi LA LEY", w: "jurimetria.laleynext.es", g: null, ci: "Madrid", c: "bd", ia: 1, nu: 0, d: "Analítica jurisprudencial predictiva" },
    { n: "Emérita Legal", e: "Emérita Legal", w: "emerita.legal", g: null, ci: "Santiago de Compostela", c: "bd", ia: 1, nu: 0, d: "Jurimetría y ranking de abogados por resultados" },

    // ——— Ciberseguridad, Privacidad, Compliance ———
    { n: "Complylaw Privacidad", e: "Aranzadi LA LEY", w: "aranzadilaley.es", g: "complylaw-privacidad", ci: "Madrid", c: "ciber", ia: 0, nu: 0, d: "Cumplimiento RGPD/LOPDGDD y evaluaciones de impacto" },
    { n: "ComplyLaw Canal Ético", e: "Aranzadi LA LEY", w: "aranzadilaley.es", g: "complylaw-canal-etico", ci: "Madrid", c: "ciber", ia: 0, nu: 0, d: "Canal de denuncias conforme a la Ley del Informante" },
    { n: "Complylaw Penal", e: "Aranzadi LA LEY", w: "aranzadilaley.es", g: "complylaw-penal", ci: "Madrid", c: "ciber", ia: 0, nu: 0, d: "Gestión de riesgos penales corporativos" },
    { n: "ComplyLaw Igualdad", e: "Aranzadi LA LEY", w: "aranzadilaley.es", g: "complylaw-igualdad", ci: "Madrid", c: "ciber", ia: 0, nu: 0, d: "Elaboración y seguimiento de planes de igualdad" },
    { n: "LEX 4Web", e: "Lex Program Online S.L.", w: "lex4web.com", g: "lex-4web", ci: "Donostia", c: "ciber", ia: 0, nu: 0, d: "Gestión de consentimiento y cookies con bloqueo real" },
    { n: "Lex Canal", e: "Lex Program Online, S.L.", w: "lexcanal.com", g: "lex-canal", ci: "Donostia", c: "ciber", ia: 0, nu: 0, d: "Canal de denuncias con prueba digital forense" },
    { n: "Lawwwing", e: "Lawwwing", w: "lawwwing.com", g: "lawwwing", ci: "Barcelona", c: "ciber", ia: 0, nu: 0, d: "Cumplimiento normativo automático para webs" },
    { n: "Legal Box Plus", e: "Ocean Legaltech, S.L.", w: "legalboxplus.com", g: "legal-box-plus", ci: "Huelva", c: "ciber", ia: 0, nu: 0, d: "Textos legales dinámicos para pymes y asesorías" },
    { n: "Pridatect", e: "Pridatect, S.L.", w: "pridatect.es", g: "pridatect", ci: "Barcelona", c: "ciber", ia: 0, nu: 0, d: "Plataforma SaaS de adaptación y seguimiento RGPD" },
    { n: "PymeLegal", e: "PymeLegal, S.L.", w: "pymelegal.es", g: "pymelegal", ci: "Barcelona", c: "ciber", ia: 0, nu: 0, d: "Protección de datos y marcas para pymes; marca blanca" },
    { n: "Youforget.me", e: "Youforget.me, S.L.", w: "youforget.me", g: "youforget-me", ci: "Sevilla", c: "ciber", ia: 0, nu: 0, d: "Tramitación de derechos digitales y privacidad" },
    { n: "Biometric Vox", e: "Biometric Vox, S.L.", w: "biometricvox.com", g: "biometric-vox", ci: "Murcia", c: "ciber", ia: 1, nu: 0, d: "Firma avanzada y autenticación por biometría de voz" },
    { n: "Camerfirma", e: "AC Camerfirma, S.A.", w: "camerfirma.com", g: "camerfirma", ci: "Madrid", c: "ciber", ia: 0, nu: 0, d: "Autoridad de certificación de las Cámaras de Comercio" },
    { n: "CertySign", e: "Customer Comms Tecknalia, S.L.", w: "certysign.com", g: "certysign", ci: "Madrid", c: "ciber", ia: 0, nu: 0, d: "Comunicaciones y transacciones certificadas multicanal" },
    { n: "CodeContract", e: "CodeContract S.L.", w: "codecontract.io", g: "codecontract", ci: "Bilbao", c: "ciber", ia: 0, nu: 0, d: "Evidencias digitales con blockchain" },
    { n: "Coloriuris", e: "Coloriuris, S.L.", w: "coloriuris.net", g: "coloriuris", ci: "Zaragoza", c: "ciber", ia: 0, nu: 0, d: "Prestador cualificado de servicios de confianza eIDAS" },
    { n: "Didit", e: "Didit, S.L.", w: "didit.me", g: "didit", ci: "Barcelona", c: "ciber", ia: 1, nu: 0, d: "Verificación de identidad KYC gratuita e ilimitada" },
    { n: "Docuten", e: "Docuten Tech S.L.", w: "docuten.com", g: "docuten", ci: "A Coruña", c: "ciber", ia: 0, nu: 0, d: "Firma digital y factura electrónica para empresas sin papel" },
    { n: "EMOZ", e: "Collarium Tech, S.L.", w: "emoz.io", g: "emoz", ci: "Barcelona", c: "ciber", ia: 0, nu: 0, d: "Huella de tiempo inmutable en blockchain para creaciones" },
    { n: "Evicertia", e: "Evidencias Certificadas S.L.", w: "evicertia.com", g: "evicertia", ci: "Madrid", c: "ciber", ia: 0, nu: 0, d: "Firma, comunicación fehaciente y certificación electrónica" },
    { n: "GoCertius", e: "EAD Trust, S.L.", w: "gocertius.com", g: "gocertius", ci: "Madrid", c: "ciber", ia: 0, nu: 0, d: "Certificación de fotos y vídeos con sello de tiempo cualificado" },
    { n: "Lefebvre Firma", e: "Lefebvre", w: "lefebvre.es", g: "lefebvre-firma", ci: "Madrid", c: "ciber", ia: 0, nu: 0, d: "Transacciones electrónicas con validez legal" },
    { n: "Lleida.net", e: "Lleida Networks, S.A.", w: "lleida.net", g: "lleida-net", ci: "Lleida", c: "ciber", ia: 0, nu: 0, d: "Notificación y contratación electrónica certificada, eIDAS" },
    { n: "Logalty", e: "Logalty, S.L.", w: "logalty.com", g: "logalty", ci: "Madrid", c: "ciber", ia: 0, nu: 0, d: "Prueba por interposición en transacciones online" },
    { n: "MailCertificado", e: "Servicios de Mailcertificado, S.L.", w: "mailcertificado.com", g: "mailcertificado", ci: "Madrid", c: "ciber", ia: 0, nu: 0, d: "Tercero de confianza: firma y comunicación certificada" },
    { n: "Punto Neutro", e: "Punto Neutro, S.L.", w: "puntoneutro.net", g: "punto-neutro", ci: "Barcelona", c: "ciber", ia: 0, nu: 0, d: "Comunicaciones certificadas y custodia de archivos" },
    { n: "Red Points", e: "Red Points Solutions, S.L.", w: "redpoints.com", g: "red-points", ci: "Barcelona", c: "ciber", ia: 1, nu: 0, d: "Protección de marca y propiedad intelectual online" },
    { n: "Repscan", e: "Repscan Technology S.L.", w: "repscan.com", g: "repscan", ci: "Barcelona", c: "ciber", ia: 1, nu: 0, d: "Detección y retirada de contenido dañino en la red" },
    { n: "Safe Evidence", e: "Pons IP", w: "ponsip.com", g: "safe-evidence", ci: "Madrid", c: "ciber", ia: 0, nu: 0, d: "Depósito y firma de archivos con blockchain (Pons IP)" },
    { n: "Alerta", e: "Pons IP", w: "ponsip.com", g: "alerta", ci: "Madrid", c: "ciber", ia: 0, nu: 0, d: "Vigilancia y protección integral de marcas" },
    { n: "SaveTheProof", e: "Full Digital S.L.", w: "savetheproof.com", g: "savetheproof", ci: "Barcelona", c: "ciber", ia: 0, nu: 0, d: "Certificación con validez legal de webs y ficheros" },
    { n: "Signaturit", e: "Signaturit Solutions, S.L.", w: "signaturit.com", g: "signaturit", ci: "Barcelona", c: "ciber", ia: 0, nu: 0, d: "Firma electrónica, entrega certificada e identificación" },
    { n: "SigneBlock", e: "SigneBlock, S.A.", w: "signeblock.com", g: "signeblock", ci: "Madrid", c: "ciber", ia: 1, nu: 0, d: "Certificación con blockchain, IoT, IA y data analytics" },
    { n: "Validated ID", e: "Validated ID, S.L.", w: "validatedid.com", g: "validated-id", ci: "Barcelona", c: "ciber", ia: 0, nu: 0, d: "VidSigner (firma), VidChain (identidad), SP4i (factura)" },
    { n: "Veridas", e: "Veridas Digital Authentication, S.L.", w: "veridas.com", g: "veridas", ci: "Pamplona", c: "ciber", ia: 1, nu: 0, d: "Biometría facial y de voz para verificación de identidad" },
    { n: "eEvidence", e: "Pricewin Networks, S.L.", w: "eevid.com", g: "eevidence", ci: "Barcelona", c: "ciber", ia: 0, nu: 0, d: "Entrega electrónica certificada eIDAS" },
    { n: "nebulaSUITE", e: "Víntegris, S.L.", w: "vintegris.com", g: "nebulasuite", ci: "Barcelona", c: "ciber", ia: 0, nu: 0, d: "Identidad digital todo en uno, prestador cualificado" },
    { n: "Burninstone", e: "Sistemas Integrados y Mejora Continua, S.L.", w: "burninstone.com", g: "burninstone", ci: "Madrid", c: "ciber", ia: 0, nu: 0, d: "Blockchain y compliance para el buen gobierno" },
    { n: "Canal Denuncias", e: "Procesia + IDBO Consultants", w: "canaldenuncias.com", g: "canal-denuncias", ci: "Madrid", c: "ciber", ia: 0, nu: 0, d: "Canal de denuncias en la nube para todo tipo de empresas" },
    { n: "Centinela", e: "Lefebvre", w: "lefebvre.es", g: "centinela", ci: "Madrid", c: "ciber", ia: 0, nu: 0, d: "Identificación, control y prevención de riesgos (ISO 19600)" },
    { n: "CompaaS Compliance", e: "Lawtory, S.L.", w: "lawtory.com", g: "compaas-compliance", ci: "Madrid", c: "ciber", ia: 0, nu: 0, d: "Plataforma integral de cumplimiento normativo" },
    { n: "Cumpleo", e: "Cumpleo, S.L.", w: "cumpleo.com", g: "cumpleo", ci: "Madrid", c: "ciber", ia: 1, nu: 1, d: "Compliance automatizado para pymes: auditoría gratuita en 3 minutos" },
    { n: "GlobalSuite Solutions", e: "Audisec, S.L.", w: "globalsuitesolutions.com", g: "globalsuite-solutions", ci: "Madrid", c: "ciber", ia: 0, nu: 0, d: "GRC: riesgos, cumplimiento y continuidad de negocio" },
    { n: "Pibisi", e: "Procera Technologia, S.L.", w: "pibisi.com", g: "pibisi", ci: "Madrid", c: "ciber", ia: 0, nu: 0, d: "Prevención de blanqueo: screening AML y KYC" },
    { n: "Tirant Compliancers", e: "Editorial Tirant lo Blanch", w: "tirant.com", g: "tirant-compliancers", ci: "Valencia", c: "ciber", ia: 0, nu: 0, d: "Programas de compliance penal para pymes" },
    { n: "Tirant Igualdad", e: "Editorial Tirant lo Blanch", w: "tirant.com", g: "tirant-igualdad", ci: "Valencia", c: "ciber", ia: 0, nu: 0, d: "Herramienta para planes de igualdad" },
    { n: "Ulises GRC", e: "Ulises GRC S.L.", w: "ulisesgrc.com", g: "ulises-grc", ci: "Barcelona", c: "ciber", ia: 0, nu: 0, d: "Gestión de riesgos y cumplimiento multinormativa en la nube" },
    { n: "icloudCompliance", e: "Klab Corporate PM S.L.", w: "icloudcompliance.com", g: "icloud-compliance", ci: "Valencia", c: "ciber", ia: 0, nu: 0, d: "GRC: auditorías, riesgos y cumplimiento centralizados" },
    { n: "Golden Owl", e: "Golden Owl", w: "goldenowl.ai", g: null, ci: "Alicante", c: "ciber", ia: 1, nu: 1, d: "Inteligencia de riesgos y monitorización regulatoria con IA" },
    { n: "Certifydoc", e: "Andifyou, S.L.", w: "certifydoc.eu", g: "certifydoc", ci: null, pais: null, c: "ciber", ia: 0, nu: 0, d: "Relevancia legal para fotos, vídeos y documentos" },
    { n: "Visualeo", e: "Visualeo Verifications, S.L.", w: "visualeo.es", g: "visualeo", ci: null, pais: null, c: "ciber", ia: 0, nu: 0, d: "Evidencias digitales inmutables de fotos y vídeos" },
    { n: "CamoText", e: "CamoText LLC", w: "camotext.ai", g: "camotext", ci: null, pais: "EE. UU.", c: "ciber", ia: 1, nu: 0, d: "Anonimización local de documentos y metadatos" },
    { n: "Metawash", e: "Suments Data LTD", w: "metawash.io", g: "metawash", ci: null, pais: "Irlanda", c: "ciber", ia: 0, nu: 0, d: "Limpieza de metadatos en archivos y webs" },
    { n: "Verics", e: "Suments Data LTD", w: "verics.io", g: "verics", ci: null, pais: "Irlanda", c: "ciber", ia: 0, nu: 0, d: "Detección de fugas de datos en sitios web" },
    { n: "Firmamex", e: "Firmamex Technologies", w: "firmamex.com", g: "firmamex", ci: null, pais: "México", c: "ciber", ia: 0, nu: 0, d: "Firma electrónica y digital global" },
    { n: "Mitek", e: "Mitek Systems, Inc.", w: "miteksystems.com", g: "mitek", ci: null, pais: "EE. UU.", c: "ciber", ia: 1, nu: 0, d: "Captura móvil y verificación de identidad digital" },
    { n: "Signatura", e: "Consentio Inc.", w: "signatura.com", g: "signatura", ci: null, pais: "Argentina", c: "ciber", ia: 0, nu: 0, d: "Firma electrónica avanzada con blockchain" },
    { n: "Vaultinum", e: "Vaultinum SARL", w: "vaultinum.com", g: "vaultinum-ip-deposit", ci: null, pais: "Suiza", c: "ciber", ia: 0, nu: 0, d: "Depósito de activos digitales y prueba de autoría" },
    { n: "OneTrust", e: "OneTrust LLC", w: "onetrust.com", g: "onetrust", ci: null, pais: "EE. UU.", c: "ciber", ia: 1, nu: 0, d: "Privacidad, riesgo tecnológico y gobernanza de datos e IA" },
    { n: "EQS Integrity Line", e: "EQS Group AG", w: "eqs.com", g: "eqs-integrity-line", ci: null, pais: "Alemania", c: "ciber", ia: 0, nu: 0, d: "Canal de denuncias seguro y confidencial" },
    { n: "RegLab", e: "RegLab", w: "reglab.nl", g: "reglab", ci: null, pais: "Países Bajos", c: "ciber", ia: 0, nu: 0, d: "Automatización de aceptación de clientes y PBC-FT" },

    // ——— Legal DigComp (formación) ———
    { n: "Diploma LegalTech UCM", e: "Escuela de Práctica Jurídica, UCM", w: "epj.ucm.es", g: "legaltech-y-transformacion-digital", ci: "Madrid", c: "digcomp", ia: 0, nu: 0, d: "Diploma en LegalTech y transformación digital" },
    { n: "ESADE Law School", e: "ESADE", w: "esade.edu", g: "esade-law-school", ci: "Barcelona", c: "digcomp", ia: 0, nu: 0, d: "Formación en derecho, tecnología e innovación" },
    { n: "UAX Business & Tech", e: "Universidad Alfonso X el Sabio", w: "uax.com", g: "uax-business-tech", ci: "Madrid", c: "digcomp", ia: 0, nu: 0, d: "Facultad Business & Tech: desafíos legaltech" },
    { n: "IE Law School", e: "IE University", w: "ie.edu", g: null, ci: "Madrid", c: "digcomp", ia: 0, nu: 0, d: "Programas de innovación legal y legal operations" },

    // ——— Marketplaces jurídicos y redes de abogados ———
    { n: "elAbogado", e: "Elabogado Directories, S.L.", w: "elabogado.com", g: "elabogado", ci: "Barcelona", c: "marketplace", ia: 0, nu: 0, d: "Directorio y captación de clientes para abogados" },
    { n: "Legal Pigeon", e: "Legal Pigeon S.L.", w: "legalpigeon.com", g: "legalpigeon", ci: "Barcelona", c: "marketplace", ia: 0, nu: 0, d: "Red de sustituciones procesales entre abogados" },
    { n: "easyoffer", e: "easyoffer", w: "easyoffer.es", g: null, ci: "Madrid", c: "marketplace", ia: 0, nu: 0, d: "Marketplace de presupuestos de abogados" },
    { n: "Lexgoapp", e: "LexGoApp S.L.", w: "lexgoapp.com", g: null, ci: "Zaragoza", c: "marketplace", ia: 0, nu: 0, d: "App que conecta clientes con abogados" },
    { n: "Legalify", e: "Legalify SAS", w: "legalify.app", g: "legalify", ci: null, pais: "Argentina", c: "marketplace", ia: 0, nu: 0, d: "Plataforma de conexión con abogados" },

    // ——— Servicios jurídicos online ———
    { n: "LexaGo", e: "Lexa M.0 S.L.", w: "lexago.es", g: "lexago", ci: "Pamplona", c: "online", ia: 1, nu: 0, d: "Apoyo jurídico-documental al laboralista; Lexa Go 3.0 con IA (2026)" },
    { n: "Pigeon OnCall", e: "Legal Pigeon S.L.", w: "legalpigeon.com", g: "pigeon-oncall", ci: "Barcelona", c: "online", ia: 0, nu: 0, d: "Consultas jurídicas online bajo demanda" },
    { n: "Reclamaclick", e: "Reclamaclick, S.L.", w: "reclamaclick.com", g: "reclamaclick", ci: "Madrid", c: "online", ia: 0, nu: 0, d: "Reclamaciones online para consumidores" },
    { n: "Reclamador", e: "Reclamador.es", w: "reclamador.es", g: null, ci: "Madrid", c: "online", ia: 1, nu: 0, d: "Reclamaciones de vuelos, banca y multas con filtrado IA" },
    { n: "Legálitas", e: "Legálitas Asistencia Legal", w: "legalitas.com", g: null, ci: "Madrid", c: "online", ia: 1, nu: 0, d: "Asistencia jurídica para particulares con asistentes IA" },
    { n: "ExtranjeriaClara", e: "ExtranjeriaClara.com", w: "extranjeriaclara.com", g: null, ci: null, pais: null, c: "online", ia: 0, nu: 1, d: "Trámites de extranjería simplificados con automatización" },

    // ——— Software de gestión de despachos y asesorías ———
    { n: "Absia Legaltech", e: "Absia Legaltech, S.L.", w: "absialegaltech.com", g: "absia-legaltech", ci: "Madrid", c: "gestion", ia: 1, nu: 1, d: "Despacho virtual de asistentes IA: hiperautomatización legal" },
    { n: "Aranzadi Fusión", e: "Aranzadi LA LEY", w: "aranzadilaley.es", g: "aranzadi-fusion", ci: "Madrid", c: "gestion", ia: 0, nu: 0, d: "Gestión integral del despacho con LexNET y eJusticia" },
    { n: "Aranzadi One", e: "Aranzadi LA LEY", w: "aranzadilaley.es", g: "aranzadi-one", ci: "Madrid", c: "gestion", ia: 0, nu: 0, d: "Gestión + base de datos para despachos pequeños" },
    { n: "Becca Software", e: "Becca Software, S.L.", w: "beccasoftware.com", g: "becca-software", ci: "Madrid", c: "gestion", ia: 0, nu: 0, d: "Gestión para profesionales y pequeñas empresas" },
    { n: "Cegid Diez ERPDespacho", e: "SDM Programas, S.L.", w: "cegid.com", g: "erpdiez-despacho", ci: "Santander", c: "gestion", ia: 0, nu: 0, d: "Suite laboral, contable y fiscal para despachos" },
    { n: "Iuritex 360º", e: "EMC Soluciones Legaltech", w: "emc.es", g: "iuritex-360o", ci: "Barcelona", c: "gestion", ia: 0, nu: 0, d: "Gestión integral + módulos de automatización" },
    { n: "Iuritex Procurador", e: "EMC Soluciones Legaltech", w: "emc.es", g: "iuritex-procurador", ci: "Barcelona", c: "gestion", ia: 0, nu: 0, d: "Gestión integral de despachos de procuradores" },
    { n: "Sísifo", e: "EMC Soluciones Legaltech", w: "emc.es", g: "sisifo", ci: "Barcelona", c: "gestion", ia: 0, nu: 0, d: "Consulta de cuentas de consignación judicial" },
    { n: "Kleos", e: "Wolters Kluwer Legal Software", w: "wolterskluwer.com", g: "kleos", ci: "Madrid", c: "gestion", ia: 1, nu: 0, d: "Gestión jurídica en la nube; Kleos Expert AI (2026)" },
    { n: "Kmaleon", e: "Wolters Kluwer Legal Software", w: "wolterskluwer.com", g: "kmaleon-abogados", ci: "Madrid", c: "gestion", ia: 0, nu: 0, d: "Gestión de expedientes para abogados y procuradores" },
    { n: "Legisway Advisor", e: "Wolters Kluwer Legal Software", w: "wolterskluwer.com", g: "legisway", ci: "Madrid", c: "gestion", ia: 0, nu: 0, d: "Software modular para departamentos jurídicos" },
    { n: "LPM Abogados", e: "Imagine Consulting, S.L.", w: "imagineconsulting.es", g: "lpm-abogados", ci: "Madrid", c: "gestion", ia: 0, nu: 0, d: "GD + iDOC + CRM + contabilidad, on premise o Azure" },
    { n: "Lex-ON", e: "Lefebvre", w: "lefebvre.es", g: "lex-on", ci: "Madrid", c: "gestion", ia: 0, nu: 0, d: "Gestión de despachos integrada con bases Lefebvre" },
    { n: "Client Link", e: "Lefebvre", w: "lefebvre.es", g: "client-link", ci: "Madrid", c: "gestion", ia: 0, nu: 0, d: "Marketing y comunicación digital del despacho" },
    { n: "Lextools", e: "pfsGROUP", w: "lextools.es", g: "lextools", ci: "Madrid", c: "gestion", ia: 0, nu: 0, d: "Centro de mando del despacho, +25 años en el sector" },
    { n: "MN Program", e: "MN Program Holding, S.L.", w: "mnprogram.com", g: "mn-program", ci: "A Coruña", c: "gestion", ia: 0, nu: 0, d: "Expedientes, agenda, facturación y contabilidad" },
    { n: "Nubbius", e: "Legalgeeks S.L.", w: "nubbius.com", g: "nubbius", ci: "Alicante", c: "gestion", ia: 0, nu: 0, d: "Gestión en la nube integrada con Office 365 y G Suite" },
    { n: "Ofionline", e: "Gestión Ofionline, S.L.", w: "ofionline.com", g: "ofionline-abogados-y-procuradores", ci: "Murcia", c: "gestion", ia: 0, nu: 0, d: "Gestión para abogados y procuradores desde 15 €/mes" },
    { n: "Sherwood", e: "Little John, S.L.", w: "littlejohn.legal", g: "sherwood-gestor-de-operaciones-legales", ci: "Madrid", c: "gestion", ia: 0, nu: 0, d: "Gestor de operaciones legales con datos estructurados" },
    { n: "Rewards Discovery", e: "Little John, S.L.", w: "littlejohn.legal", g: "rewards-discovery-captacion-de-negocio", ci: "Madrid", c: "gestion", ia: 0, nu: 0, d: "Admisión de asuntos y captación de clientes" },
    { n: "Tirant Gestión", e: "Editorial Tirant lo Blanch", w: "tirant.com", g: "tirant-gestion-de-despachos", ci: "Valencia", c: "gestion", ia: 0, nu: 0, d: "Gestión de despachos con integraciones a medida" },
    { n: "iusUp", e: "Awerty Servicios Informáticos, S.L.", w: "iusup.com", g: "iusup", ci: "Barcelona", c: "gestion", ia: 0, nu: 0, d: "Gestión basada en tecnologías Microsoft 365" },
    { n: "Accordly", e: "Accordly", w: "accordly.es", g: "accordly", ci: "Sevilla", c: "gestion", ia: 0, nu: 1, d: "Gestión digital de MASC conforme a la Ley 1/2025" },
    { n: "Apud Acta", e: "Bewor Tech, S.L.", w: "apudacta.com", g: "apud-acta", ci: "Granada", c: "gestion", ia: 0, nu: 0, d: "Apoderamientos electrónicos sin certificado digital" },
    { n: "Claimbnb", e: "Claimbnb 18, S.L.", w: "claimbnb.com", g: "claimbnb", ci: "Madrid", c: "gestion", ia: 0, nu: 0, d: "Financiación de litigios para despachos y clientes" },
    { n: "Gioconda", e: "Aranzadi LA LEY", w: "aranzadilaley.es", g: "gioconda", ci: "Madrid", c: "gestion", ia: 0, nu: 0, d: "Gestión integral de concursos de acreedores" },
    { n: "Pagoscertificados.com", e: "Sistema de Pagos Certificados, S.L.", w: "pagoscertificados.com", g: "pagoscertificados-com", ci: "Madrid", c: "gestion", ia: 0, nu: 0, d: "Acuerdos de pago judiciales y extrajudiciales online" },
    { n: "Probus", e: "ISID, S.L.", w: "isid.es", g: "probus", ci: "Madrid", c: "gestion", ia: 1, nu: 0, d: "Transcripción y gestión de vistas judiciales con IA" },
    { n: "IActa", e: "ISID, S.L.", w: "isid.es", g: "iacta", ci: "Madrid", c: "gestion", ia: 0, nu: 0, d: "Videoactas de plenos y consejos de administración" },
    { n: "Registro de Impagados Judiciales", e: "Desarrollo de Aplicaciones Jurídicas, S.L.", w: "registrodeimpagados.org", g: "registro-de-impagados-judiciales", ci: "Madrid", c: "gestion", ia: 0, nu: 0, d: "Fichero de morosidad con resolución judicial firme" },
    { n: "Boardchain", e: "CYSAE Severla, S.L.", w: "cysae.com", g: "boardchain", ci: "Madrid", c: "gestion", ia: 0, nu: 0, d: "Juntas de socios con blockchain" },
    { n: "Councilbox", e: "Councilbox Technology, S.L.", w: "councilbox.com", g: "councilbox", ci: "Vigo", c: "gestion", ia: 0, nu: 0, d: "Reuniones societarias y votaciones remotas con blockchain" },
    { n: "MIA", e: "Ecix Group, S.L.", w: "ecix.com", g: "mia", ci: "Madrid", c: "gestion", ia: 1, nu: 0, d: "RegTech con machine learning para evitar sanciones" },
    { n: "Parallel Profiles", e: "Parallel Solutions, S.L.", w: "byparallel.com", g: "parallel-profiles", ci: "Barcelona", c: "gestion", ia: 0, nu: 0, d: "CRM para equipos legales con alertas contractuales" },
    { n: "Sttok", e: "Sttok Barcelona, S.L.", w: "sttok.com", g: "sttok", ci: "Barcelona", c: "gestion", ia: 0, nu: 0, d: "Gestión de sociedades: captable, juntas, stock options" },
    { n: "Nymiz", e: "Nymiz Software Company, S.L.", w: "nymiz.com", g: "nymiz", ci: "Bilbao", c: "gestion", ia: 1, nu: 0, d: "Anonimización de datos personales con IA" },
    { n: "Salatan.io", e: "Salatan Abogados", w: "salatan.io", g: "salatan-io", ci: "Barcelona", c: "gestion", ia: 1, nu: 0, d: "CRM con agentes IA y lectura de notificaciones judiciales" },
    { n: "Focus Legal", e: "Focusfera", w: "focusfera.com", g: "focus-legal", ci: "Santander", c: "gestion", ia: 0, nu: 0, d: "Gestión integral para despachos y autónomos" },
    { n: "Freshdesk (Optima)", e: "Optima Solutions", w: "optimasolutions.es", g: "freshdesk", ci: "Madrid", c: "gestion", ia: 0, nu: 0, d: "Atención omnicanal centralizada para despachos" },
    { n: "Legal Risk Scanner", e: "DAS Seguros", w: "das.es", g: "legal-risk-scanner", ci: "Madrid", c: "gestion", ia: 1, nu: 0, d: "Diagnóstico de riesgos legales de pymes con IA" },
    { n: "Juiciator", e: "Juiciator", w: "juiciator.com", g: "juiciator", ci: null, pais: null, c: "gestion", ia: 0, nu: 0, d: "Gestión y automatización de despachos en la nube" },
    { n: "Legalyzee", e: "Digital Wessy, S.L.", w: "legalyzee.com", g: "legalyzee", ci: null, pais: null, c: "gestion", ia: 0, nu: 0, d: "Marketplace para rentabilizar documentos legales" },
    { n: "Lexdigo", e: "LegalMit, S.L.", w: "lexdigo.com", g: "lexdigo", ci: null, pais: null, c: "gestion", ia: 0, nu: 0, d: "Despacho 360º: comunicación y gestión para firmas" },
    { n: "Sudespacho.net", e: "DSIP, S.L.", w: "sudespacho.net", g: "sudespacho-net", ci: null, pais: null, c: "gestion", ia: 0, nu: 0, d: "Gestión de despachos en la nube por módulos" },
    { n: "DigaLaw X", e: "SpeechWare", w: "speechware.be", g: "digalaw", ci: null, pais: "Bélgica", c: "gestion", ia: 1, nu: 0, d: "Reconocimiento de voz inteligente para juristas" },
    { n: "Amberlo", e: "Amberlo Limited", w: "amberlo.io", g: "amberlo", ci: null, pais: "Irlanda", c: "gestion", ia: 0, nu: 0, d: "Gestión 360º de clientes, casos y finanzas en la nube" },
    { n: "BaseNet", e: "BaseNet Internet Projects BV", w: "basenet.es", g: "basenet", ci: null, pais: "Países Bajos", c: "gestion", ia: 0, nu: 0, d: "Gestión integral 360 en la nube" },
    { n: "Crespect", e: "Crespect OÜ", w: "crespect.com", g: "crespect", ci: null, pais: "Estonia", c: "gestion", ia: 0, nu: 0, d: "Gestión + CRM todo en uno para despachos" },
    { n: "HighQ", e: "Thomson Reuters", w: "thomsonreuters.com", g: "highq", ci: "Madrid", c: "gestion", ia: 0, nu: 0, d: "Legal project management y automatización" },
    { n: "Legal One", e: "Thomson Reuters", w: "thomsonreuters.com", g: "legal-one", ci: "Madrid", c: "gestion", ia: 0, nu: 0, d: "Ecosistema para asuntos legales de empresa" },
    { n: "Intapp DealCloud", e: "Integration Appliance, Inc.", w: "intapp.com", g: "intapp-dealcloud", ci: null, pais: "EE. UU.", c: "gestion", ia: 1, nu: 0, d: "CRM+ para firmas: relaciones, negocio y analítica con IA" },
    { n: "DiliTrust Governance", e: "DiliTrust", w: "dilitrust.com", g: "dilitrust-governance", ci: null, pais: "Francia", c: "gestion", ia: 0, nu: 0, d: "Gestión jurídica integral para departamentos legales" },
    { n: "Litera Compare", e: "Litera", w: "litera.com", g: "litera-compare", ci: null, pais: "EE. UU.", c: "gestion", ia: 0, nu: 0, d: "Comparación de documentos líder del mercado" },
    { n: "iManage Work", e: "iManage LLC", w: "imanage.com", g: "imanage-work", ci: null, pais: "EE. UU.", c: "gestion", ia: 0, nu: 0, d: "Gestor documental integrado en Office y Outlook" },
    { n: "Introhive", e: "Introhive Services Inc.", w: "introhive.com", g: "introhive", ci: null, pais: "Canadá", c: "gestion", ia: 1, nu: 0, d: "Datos de relaciones con IA para desarrollo de negocio" },
    { n: "TIQ Time", e: "Tiq B.V.", w: "tiqtime.com", g: "tiq-time", ci: null, pais: "Países Bajos", c: "gestion", ia: 0, nu: 0, d: "Registro de tiempo consistente para abogados" }
  ]
};
